### ISSUE TITLE
Add support for Dawnscanner

### ISSUE THREAD

**Issue by thesp0nge** [OWASP/pipeline#18]
I'm in a conflict of interest here, close this one if not appropriated. 
It might be a good idea to add support for dawnscanner ruby static analysis tool I wrote also. The main difference with brakeman is that dawnscanner, is MVC framework agnostic so it works also for Sinatra, Padrino, pure rack applications and Lotus in the future.

Could be a great way to improve the tool and improve the pipeline as well.

**Comment by 10dot** [comment]
I've already got some code written to test dawnscanner... so expect a PR for just this thing maybe next week-ish.

**Comment by 10dot** [comment]
This is fixed by #20 .
